version: "3"

services:
  v2ray:
    image: ghcr.io/athecoder/v2fly-core:v5.1.0
    restart: always
    ports:
      - "1310:1310"
    volumes:
      - ./config/:/etc/v2ray/
      - ./logs:/var/log/v2ray/
