version: "3"

services:
  v2ray:
    image: ghcr.io/getimages/v2fly-core:v5.1.0
    container_name: v2ray_upstream
    restart: always
    ports:
      - ${VMESS_PORT:-1310}:1310
    volumes:
      - ./config/:/etc/v2ray/
      - ./logs:/var/log/v2ray/
