version: "3"

services:
  v2ray:
    image: ghcr.io/athecoder/v2fly-core:v5.1.0
    restart: halways
    environment:
      - v2ray.vmess.aead.forced=false
    ports:
      - "127.0.0.1:1010:1010"
      - "127.0.0.1:1010:1010/udp"
      - "127.0.0.1:1110:1110"
      - "1210:1210"
      - "1210:1210/udp"
      - "1310:1310"
    volumes:
      - ./config/:/etc/v2ray/
      - ./logs:/var/log/v2ray/
