version: "3"

services:
  v2ray:
    image: ghcr.io/getimages/v2fly-core:v4.45.2
    restart: always
    environment:
      - v2ray.vmess.aead.forced=false
    expose:
      - 1010
      - 1010/udp
      - 1110
    volumes:
      - ./config/:/etc/v2ray/
      - ./logs:/var/log/v2ray/